server:
  port: 9009
spring:
  application:
    name: tensquare\sms #指定服务名
  rabbitmq:
    host: 192.168.243.128
aliyun:
  sms:
    accessKeyId: LTAI4FtugJV5Gy8qCsNYeY8S
    accessKeySecret: NRfHkWXuoEepQxLb++sGuYMNvDEi8jpZ
    template_code: SMS_173472841 
    sign_name: 十次方论坛